version: '3'


services:
  architext:
    build: ./server/
    restart: always
    ports:
      - "2112:2112"
    depends_on:
      - architext-db
    volumes:
      - ./volumes/architext/logs:/usr/src/app/logs
    
  architext-db:
    image: mongo
    restart: always
    volumes:
      - ./volumes/architext/db:/data/db
