version: '3'

services:
  reverse-proxy:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./home.html:/usr/share/nginx/html/home.html:ro
    - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
    - "80:80"
    - "443:443"
    - "5000:5000"
    depends_on:
    - client
    - server

  server:
    build: ./server/
    restart: always
    expose:
      - "5000"
    depends_on:
      - db
    volumes:
      - ./volumes/architext/logs:/usr/src/app/logs
      - ./server/en_config.yml:/usr/src/app/config.yml
    environment:
      - DB_HOST=db  # host that holds the database
      - DATABASE=architext    # name of db in the host
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

  server_es:
    build: ./server/
    restart: always
    expose:
      - "5000"
    depends_on:
      - db
    volumes:
      - ./volumes/architext/logs:/usr/src/app/logs
      - ./server/es_config.yml:/usr/src/app/config.yml
    environment:
      - DB_HOST=db  # host that holds the database
      - DATABASE=architext-es    # name of db in the host
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

  client:
    build:
      context: ./client/architext-client
      dockerfile: Dockerfile
      args:
        - SERVER_ADDRESS=${SERVER_ADDRESS}
        - BASE_PATH=/
    restart: always
    expose:
      - "80"

  client_es:
    build:
      context: ./client/architext-client
      dockerfile: Dockerfile
      args:
        - SERVER_ADDRESS=${ES_SERVER_ADDRESS}
        - BASE_PATH=/es/
    restart: always
    expose:
      - "80"

  db:
    image: mongo
    restart: always
    volumes:
      - ./volumes/architext/db:/data/db
