version: '3'


services:
  architext:
    build: ./server/
    restart: always
    ports:
      - "2112:2112"
    depends_on:
      - architext-db
    volumes:
      - ./volumes/architext/logs:/usr/src/app/logs
      - ./server:/usr/src/app  # Develop
    environment:
      - DB_HOST=architext-db  # host that holds the database 
      - DATABASE=architext    # name of db in the host
    
  architext-db:
    image: mongo
    restart: always
    volumes:
      - ./volumes/architext/db:/data/db
