services:
  architext_backend:
    build: ./server/
    restart: always
    expose:
      - "3000"
    depends_on:
      - architext_db
    volumes:
      - ./volumes/architext/logs:/usr/src/app/logs
      - ./server/en_config.yml:/usr/src/app/config.yml
    environment:
      - DB_HOST=architext_db  # host that holds the database
      - DATABASE=architext    # name of db in the host
      - ALLOWED_ORIGINS=${ARCHITEXT_SERVER_ALLOWED_ORIGINS}

  architext_backend_es:
    build: ./server/
    restart: always
    expose:
      - "5000"
    depends_on:
      - architext_db
    volumes:
      - ./volumes/architext/logs:/usr/src/app/logs
      - ./server/es_config.yml:/usr/src/app/config.yml
    environment:
      - DB_HOST=architext_db  # host that holds the database
      - DATABASE=architext-es    # name of db in the host
      - ALLOWED_ORIGINS=${ARCHITEXT_SERVER_ALLOWED_ORIGINS}

  architext_web:
    build:
      context: ./client/architext-client
      dockerfile: Dockerfile
      args:
        - SERVER_ADDRESS=${ARCHITEXT_SERVER_ADDRESS}
        - BASE_PATH=${ARCHITEXT_WEB_BASE_PATH_EN}
    restart: always
    expose:
      - "80"

  architext_web_es:
    build:
      context: ./client/architext-client
      dockerfile: Dockerfile
      args:
        - SERVER_ADDRESS=${ARCHITEXT_SERVER_ADDRESS_ES}
        - BASE_PATH=${ARCHITEXT_WEB_BASE_PATH_ES}
    restart: always
    expose:
      - "80"

  architext_db:
    image: mongo
    restart: always
    volumes:
      - ./volumes/architext/db:/data/db
