version: '3'

services:
  server:
    build: ./server/
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./volumes/architext/logs:/usr/src/app/logs
    environment:
      - DB_HOST=db  # host that holds the database
      - DATABASE=architext    # name of db in the host

  client:
    build:
      context: ./client/architext-client
      dockerfile: Dockerfile
      args:
        - SERVER_URL=${SELF_ADDRESS}
    restart: always
    ports:
      - "80:80"

  db:
    image: mongo
    restart: always
    volumes:
      - ./volumes/architext/db:/data/db
