public_worlds_limit: 5
locale: en_US

cover: |-
  This is a text game where you can create and share any world you can imagine.
  If you are new, bear with me and discover the game in just 5 minutes :-)

sign_in_welcome: |-
  Welcome to Architext!

log_in_welcome: |-
  NEWS:
    We are still in development, you can check the source code at
    https://github.com/OliverLSanz/architext